version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Mappa la porta 3000 dal container alla porta 3000 della macchina host
    volumes:
      - .:/app  # Monta la directory del progetto sul container, per poter modificare il codice senza ricompilare
    environment:
      - NODE_ENV=development
    command: yarn dev  # Esegui il comando di sviluppo di Next.js
